In [1]:
print("hello")
      

hello


# hello

### hello

#### hello



In [51]:
import numpy as np

In [52]:
lista=[1,2,3,4,5,6,7,8]
print (lista)
print(type(lista))

[1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>


In [53]:
np_lista=np.array([1,2,3,4,5,6,7,8])
np_lista=np.array(np_lista)
print(np_lista)
print(type(np_lista))


[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [54]:
print(np_lista[0])
np_lista[2:6]

1


array([3, 4, 5, 6])

In [55]:
matrix=[[1,2,3],[4,5,3],[7,8,9]]
np_matrix=np.array(matrix)
print(np_matrix[1][2])


3


In [56]:
rand=np.random.randint(5,500, size=30)

print(rand)


[213  77 257 405 487 278  61 447 117 324 182 294 430 194  97 419 354 418
 283 498 146 377 181 146 270 340 323 305 475  86]


In [57]:
rand_filte =rand>250
rand[rand_filte]
rand[rand>250]



array([257, 405, 487, 278, 447, 324, 294, 430, 419, 354, 418, 283, 498,
       377, 270, 340, 323, 305, 475], dtype=int32)

In [60]:
print(f"SUM:{rand.sum()}")
print(f"MAX:{rand.max()}")
print(f"MIN:{rand.min()}")
print(f"mean:{rand.mean()}")

SUM:8484
MAX:498
MIN:61
mean:282.8
